### ISSUE TITLE
tpm2_unseal - ERROR: Got arguments but the tool takes no arguments

### ISSUE THREAD

**Issue by vamshim567** [tpm2-software/tpm2-tools#1819]
Hi

We are using below versions
tpm2-tools (4.0) 
tpm2-tss (2.3.1) 
tpm2-abrmd (2.2.0)

Faced weird error when using tpm2_unseal command

As mentioned in Changelog, tried to use below command

`tpm2_unseal -H 0x81010001`

Throws following error : 
tpm2_unseal: invalid option -- 'H'
Process exited with code 1

If argument passed directly as mentioned [here](https://github.com/tpm2-software/tpm2-tools/blob/master/man/common/ctxobj.md)

`tpm2_unseal 0x81010001` 

throwing error without error code:
ERROR: Got arguments but the tool takes no arguments

Please advise, Thanks.

**Comment by idesai** [comment]
Try "-c" per the [source-code](https://github.com/tpm2-software/tpm2-tools/blob/898a6d6313f849314293f046dc1444fb8ca9a5c0/tools/tpm2_unseal.c#L98)

**Comment by vamshim567** [comment]
I'm trying to use option similar to "--item" and from newer version (4.0) change log "--item" is removed and shorted with "-H"

As memtioned in above thread, when i try to use "-H", it throws an error.
As advised, i tried with "-c" : 

`tpm2_unseal -c 0x81010001` , throws below error

 WARNING:esys:../src/tss2-esys/api/Esys_Unseal.c:291:Esys_Unseal_Finish() Received TPM Error 
ERROR:esys:../src/tss2-esys/api/Esys_Unseal.c:98:Esys_Unseal() Esys Finish ErrorCode (0x00000182) 
ERROR: Esys_Unseal(0x182) - tpm:handle(1):inconsistent attributes
ERROR: Unable to run tpm2_unseal

**Comment by idesai** [comment]
@vamshim567 is this a sealing object? can you paste all the steps to reproduce including what is being made persistent at 81010001.

**Comment by vamshim567** [comment]
Here is how my steps look like

`tpm2_clear`
`tpm2_createprimary --quiet --hierarchy=o --key-algorithm=rsa --hash-algorithm=sha256 --key-context=prim.ctx`
dd if=/dev/urandom bs=1 count=32 status=none >KEY_IN 

tpm2_create --hash-algorithm=sha256 --key-algorithm=keyedhash --public=seal.pub --private=seal.priv --parent-context=prim.ctx <KEY_IN

tpm2_load --parent-context=prim.ctx --public=seal.pub --private=seal.priv --name=seal.name --key-context=seal.ctx

tpm2_evictcontrol --hierarchy=o --object-context=seal.ctx 0x81010001

tpm2_unseal 0x81010001 >KEY_OUT

sha256sum KEY_IN KEY_OUT

Thanks

**Comment by gblewis1** [comment]
So far we've only tried this with the IBM simulator version 1332: https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm1332.tar.gz  -- next will be on physical hardware.

**Comment by williamcroberts** [comment]
Two things wrong, both in tpm2_create. You need to specify -i- to take input from stdin to seal to the TPM. The second is that you also don't need to specify the keyedhash algorithm. This works:

```bash
tpm2_clear
tpm2_createprimary --quiet --hierarchy=o --key-algorithm=rsa --hash-algorithm=sha256 --key-context=prim.ctx
dd if=/dev/urandom bs=1 count=32 status=none > KEY_IN
tpm2_create --hash-algorithm=sha256 --public=seal.pub --private=seal.priv --parent-context=prim.ctx -i- < KEY_IN
tpm2_load --parent-context=prim.ctx --public=seal.pub --private=seal.priv --name=seal.name --key-context=seal.ctx
tpm2_evictcontrol --hierarchy=o --object-context=seal.ctx 0x81010001
tpm2_unseal -c 0x81010001 >KEY_OUT
sha256sum KEY_IN KEY_OUT
cmp KEY_IN KEY_OUT
```
Outputs:
```
./test.sh 
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|userwithauth
  raw: 0x52
type:
  value: keyedhash
  raw: 0x8
algorithm: 
  value: null
  raw: 0x10
keyedhash: f7cb015d66a6c05bbbff591bc2ce2b3b02d77cdee5f090b9a098262467873996
persistent-handle: 0x81010001
action: persisted
ff0f1674d4d6f96a204d949257d64ce7470fcb9444e800fae2e769ae3d1b0b70  KEY_IN
ff0f1674d4d6f96a204d949257d64ce7470fcb9444e800fae2e769ae3d1b0b70  KEY_OUT
```
