### ISSUE TITLE
[Help] What is the command to get tpm2 version infomation

### ISSUE THREAD

**Issue by tim-rj** [tpm2-software/tpm2-tools#2159]
Strange, tpm2_getpubek seems can't be found in newest release. what is the command to get tpm2 version info?

**Comment by tim-rj** [comment]
No simulator, but real TPM hardware.

**Comment by williamcroberts** [comment]
```bash
tpm2_getcap properties-fixed
```
```yaml
TPM2_PT_FAMILY_INDICATOR:
  raw: 0x322E3000
  value: "2.0"
TPM2_PT_LEVEL:
  raw: 0
TPM2_PT_REVISION:
  value: 1.62
TPM2_PT_DAY_OF_YEAR:
  raw: 0x35
TPM2_PT_YEAR:
  raw: 0x7E4
TPM2_PT_MANUFACTURER:
  raw: 0x49424D20
  value: "IBM "
TPM2_PT_VENDOR_STRING_1:
  raw: 0x53572020
  value: "SW"
TPM2_PT_VENDOR_STRING_2:
  raw: 0x2054504D
  value: "TPM"
TPM2_PT_VENDOR_STRING_3:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_STRING_4:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_TPM_TYPE:
  raw: 0x1
TPM2_PT_FIRMWARE_VERSION_1:
  raw: 0x20191023
TPM2_PT_FIRMWARE_VERSION_2:
  raw: 0x163636
```
