### ISSUE TITLE
tpm2_eventlog: Partitions are displayed incorrectly

### ISSUE THREAD

**Issue by josephlr** [tpm2-software/tpm2-tools#2746]
When running `tpm2 eventlog ./eventlog.bin` I get the following for the `EV_EFI_GPT_EVENT` `Partions:`
```yaml
Partitions:
- PartitionTypeGUID: 28732ac1-1ff8-d211-ba4b-00a0c93ec93b
  UniquePartitionGUID: 1346501a-b519-444b-a83d-d926d40daa1c
  StartingLBA: 0x800
  EndingLBA: 0x807ff
  Attributes: 0x0
  PartitionName: "E"
- PartitionTypeGUID: 28732ac1-1ff8-d211-ba4b-00a0c93ec93b
  UniquePartitionGUID: 1346501a-b519-444b-a83d-d926d40daa1c
  StartingLBA: 0x800
  EndingLBA: 0x807ff
  Attributes: 0x0
  PartitionName: "E"
- PartitionTypeGUID: 28732ac1-1ff8-d211-ba4b-00a0c93ec93b
  UniquePartitionGUID: 1346501a-b519-444b-a83d-d926d40daa1c
  StartingLBA: 0x800
  EndingLBA: 0x807ff
  Attributes: 0x0
  PartitionName: "E"
```

Note that the same partition is printed 3 times and the `PartitionName:` is only one character.

I would expect an output that looks like:
```yaml
Partitions:
- PartitionTypeGUID: 28732ac1-1ff8-d211-ba4b-00a0c93ec93b
  UniquePartitionGUID: 1346501a-b519-444b-a83d-d926d40daa1c
  StartingLBA: 0x800
  EndingLBA: 0x807ff
  Attributes: 0x0
  PartitionName: "EFI System"
- PartitionTypeGUID: 0f889da1-fc05-3b4d-a006-743f0f84911e
  UniquePartitionGUID: 2406fec3-b73d-f444-941e-49e6823d5a30
  StartingLBA: 0x80800
  EndingLBA: 0x1d24594e
  Attributes: 0x0
  PartitionName: "Linux RAID"
- PartitionTypeGUID: af3dc60f-8384-7247-8e79-3d69d8477de4
  UniquePartitionGUID: d355ca07-baef-a743-aea7-334c379e6b70
  StartingLBA: 0x1d246000
  EndingLBA: 0x1dcf328e
  Attributes: 0x0
  PartitionName: "Linux filesystem"
```
