### ISSUE TITLE
Certain Nuvoton TPM chips cause `tpm2_getcap properties-fixed` to return broken YAML

### ISSUE THREAD

**Issue by galmasi** [tpm2-software/tpm2-tools#2921]
Summary
---------

I found a Nuvoton TPM chip that causes tpm2_getcap to print "garbled" output. "Garbled" here is relative -- the output is human-readable, but is not valid YAML. Not quite sure whether the "contract" calls tpm2_getcap to always return valid YAML; hoping that the tpm2-tools team is willing to consider a fix.

How to reproduce
------------------

* Server: Lenovo SR635 server equipped with a Nuvoton TPM chip.
* O/S: Ubuntu 18.04, tpm2-tools version: tag 5.1.1 custom-packaged
* Execute: `tpm2_getcap properties-fixed`

Attaching the output from my run:

```
TPM2_PT_VENDOR_STRING_1:
  raw: 0x4E504354
  value: "NPCT"
TPM2_PT_VENDOR_STRING_2:
  raw: 0x37357800
  value: "75x"
TPM2_PT_VENDOR_STRING_3:
  raw: 0x22212134
  value: ""!!4"
TPM2_PT_VENDOR_STRING_4:
  raw: 0x726C7300
  value: "rls"
```

* **Expected outcome**: YAML output parseable by `Python` or `yq`
* **Actual outcome**: the `value` for TPM2_PT_VENDOR_STRING_3 is not valid YAML since it has an un-escaped quote character inside the string.

Request
---------

Please fix tpm2_getcap so YAML control characters inside strings are properly escaped.

Analysis
---------

* I am fairly sure that Nuvoton is not bound by any restrictions on what they can or cannot put into the vendor strings, including unprintable characters.
* Beyond the current requested fix ("please escape the quote character in YAML output"), is it even possible for tpm2-tools to always guarantee correct parseable YAML output from tpm2_getcap?
