### ISSUE TITLE
import: doesn;t respect scheme

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-tools#2997]
When importing an RSA or EC key, import doesn't respect scheme:
```bash
tpm2_import -C p.ctx -G rsa:rsassa-sha256 -i private.pem -u key.pub -r key.priv
```
```yaml
scheme:
  value: null
  raw: 0x10
```
