### ISSUE TITLE
eventlog: SbatLevel is a string not a signature

### ISSUE THREAD

**Issue by THS-on** [tpm2-software/tpm2-tools#3145]
The measurement of the SbatLevel variable with the event `EV_EFI_VARIABLE_AUTHORITY` is parsed as  `EFI_SIGNATURE_DATA` which is incorrect.

Event with the data not parsed: 
```
- EventNum: 28
  PCRIndex: 7
  EventType: EV_EFI_VARIABLE_AUTHORITY
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "922e939a5565798a5ef12fe09d8b49bf951a8e7f89a0cca7a51636693d41a34d"
  EventSize: 68
  Event:
    VariableName: 605dab50-e046-4300-abb6-3dd810dd8b23
    UnicodeNameLength: 9
    VariableDataLength: 18
    UnicodeName: SbatLevel
    VariableData: "736261742c312c323032313033303231380a"
```
The VariableData decodes to: `sbat,1,2021030218`

Parsed data:
```
- EventNum: 28
  PCRIndex: 7
  EventType: EV_EFI_VARIABLE_AUTHORITY
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "922e939a5565798a5ef12fe09d8b49bf951a8e7f89a0cca7a51636693d41a34d"
  EventSize: 68
  Event:
    VariableName: 605dab50-e046-4300-abb6-3dd810dd8b23
    UnicodeNameLength: 9
    VariableDataLength: 18
    UnicodeName: SbatLevel
    VariableData:
    - SignatureOwner: 74616273-312c-322c-3032-313033303231
      SignatureData: 380a
```
This signature is invalid and also the signature data.

**Comment by idesai** [comment]
@THS-on can we close this?

**Comment by THS-on** [comment]
@idesai  no the PR did not fix this. It was only for the MokListTrusted. I can sent a PR to fix this next week.

**Comment by snits** [comment]
I think perhaps what should happen in the code is special case the things that are known to be EFI_SIGNATURE_DATA, and perhaps the other variables that are known like MokListTrusted, and then have a general case to treat any others like a efi variable data, and just dump it.

There should also be a sanity check on the size getting passed to calloc, in case of an underflow like the failure with MokListTrusted.

**Comment by THS-on** [comment]
> I think perhaps what should happen in the code is special case the things that are known to be EFI_SIGNATURE_DATA, and perhaps the other variables that are known like MokListTrusted, and then have a general case to treat any others like a efi variable data, and just dump it.

Only parsing a known list and just dumping the rest is probably the best option. I'll do that for the PR.

**Comment by snits** [comment]
For example when tpm2_eventlog tries parsing it as a 1.2 format log it gets:

```
- EventNum: 28
  PCRIndex: 7
  EventType: EV_EFI_VARIABLE_AUTHORITY
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "922e939a5565798a5ef12fe09d8b49bf951a8e7f89a0cca7a51636693d41a34d"
  EventSize: 68
  Event:
    VariableName: 605dab50-e046-4300-abb6-3dd810dd8b23
    UnicodeNameLength: 9
    VariableDataLength: 18
    UnicodeName: SbatLevel
    VariableData: "736261742c312c323032313033303231380a"
- EventNum: 29
  PCRIndex: 7
  EventType: EV_EFI_VARIABLE_AUTHORITY
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "5f62a2107fa11ce0485fd252d2e6c603cb8ed075861f9513bfed0a26bf6ed62b"
  EventSize: 61
  Event:
    VariableName: 605dab50-e046-4300-abb6-3dd810dd8b23
    UnicodeNameLength: 14
    VariableDataLength: 1
    UnicodeName: MokListTrusted
    VariableData: "01"
```
