### ISSUE TITLE
tpm2_quote example does not work

### ISSUE THREAD

**Issue by tomoveu** [tpm2-software/tpm2-tools#3213]
I am following the steps from the `tpm2_quote example` from here https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_quote.1.md#examples

```
tpm2_createprimary -C e -c primary.ctx

tpm2_create -C primary.ctx -u key.pub -r key.priv

tpm2_load -C primary.ctx -u key.pub -r key.priv -c key.ctx

tpm2_quote -Q -c key.ctx -l 0x0004:16,17,18+0x000b:16,17,18
```

At the final step, I am receiving `multiple errors`:
* out of memory for object context
  * how is this possible with `only two keys` & context generated?
* incorrect handle value 
  * is the `-c` option changed? 
* unable to make sense of key.ctx
   * moments ago primary.ctx was used without issue, how is the lowercase `-c` option different from `-C` ?

Complete output:
```
trm@PCX:~/letstrust2go/tpm2-tools$ sudo tpm2_quote -Tspi-lt2go -Q -c key.ctx -l 0x0004:16,17,18+0x000b:16,17,18
WARNING:esys:src/tss2-esys/api/Esys_ContextLoad.c:279:Esys_ContextLoad_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_ContextLoad.c:93:Esys_ContextLoad() Esys Finish ErrorCode (0x00000902) 
ERROR: Esys_ContextLoad(0x902) - tpm:warn(2.0): out of memory for object contexts
ERROR: Incorrect handle value, got: "key.ctx", expected expected [o|p|e|n|l] or a handle number
ERROR: Unable to read PEM from provided BIO/file
ERROR: Unable to fetch public/private portions of TSS PRIVKEY
ERROR: Cannot make sense of object context "key.ctx"
ERROR: Invalid key authorization
ERROR: Unable to run tpm2_quote
```

Environment
* tpm2_tools: tool="tpm2" `version="5.5"` tctis="libtss2-tctildr" tcti-default=tcti-device
* tpm2_tss: latest master `commit 4307787cee74e51d108c2db22669c2ebaeaad399 `

cc: @williamcroberts @PaulKissinger

**Comment by williamcroberts** [comment]
> out of memory for object context
> how is this possible with only two keys & context generated?

No resource manager is being used, you probably need to run tpm2_flushcontext -lst between command invocations. This is a limitation in the tools, we wanted to add automatic flushing but never got to it, see bug #1511

> incorrect handle value

My guess is it's just a cascading error giving you incorrect ERROR output after the ContextLoad fails.

> moments ago primary.ctx was used without issue, how is the lowercase -c option different from -C ?

The general paradigm is that:
`-C` is the parent object for commands.
`-c` is the object in use for commands.

I think this is just cascading error logs that need to be cleaned up when the context load, `-c` is the right options.

**Comment by tomoveu** [comment]
Thank you for clarifying in such good detail @williamcroberts I will test with `tpm2-abrmd` and close the issue if all is good.

Two keys should not require a resource manager, but using TPM2_ContextSave/Load frequently probably is the issue as you explained.

**Comment by tomoveu** [comment]
Using latest version of `tpm2-abrmd`, the tpm2_quote example worked using LetsTrust TPM USB2GO. Output below

```
~/letstrust2go/quote-test$ sudo udevadm info -e | grep LetsTrust
E: ID_MODEL=LetsTrust-TPM2Go
E: ID_MODEL_ENC=LetsTrust-TPM2Go
E: ID_SERIAL=www.pi3g.com_LetsTrust-TPM2Go_000005
trm@PCX:~/letstrust2go/quote-test$ tpm2_quote -c key.ctx -l 0x0004:16,17,18+0x000b:16,17,18
quoted: ff54434780180022000ba979479630e39a3570ae71fd5dd7ff6470f6b7e22e8bd443755cbdcb4c0446ae0000000000000006ac96000000030000000001000700550011cb0000000002000403000007000b0300000700204657a504e2af3d6a0132b666b4d1e75a118c64cf6ac94a8f6706e390b5f03e73
signature:
  alg: rsassa
  sig: 20d810cec82ad8502aeb56ce657bec2e5fd276c2ce60ed2da9aa489a17bb0d515c5b4d36470f7420b3e668a6db94e73726bd6f9a0577145955a43ffc4c3a8f5b99246feb04c28eb1ea5afc474437dd1c19554b571456269ac0947da367a103ee0a53c627673e809efb30e143fb25c601618a586c8ec5a3d881b1872f8c6a1f6033270c71268ded3739ecae24fd4c2232c2c42de70ff4ed5242e1b48c3b13aaa34a54fbff614fc9a7b1fd2a550accdf2920259b44485af4264a5c181e434868d01cd9563f7fdeaf142f6df604f23e18f563fcff31ec4b07f404eaa7961e93e800aaa3479e055b5b0509b575dfbde87916022cb5ab958d268a517542b7a88bbc16
trm@PCX:~/letstrust2go/quote-test$ 
```

Thanks again @williamcroberts and kudos @PaulKissinger
