### ISSUE TITLE
how to get the AES symmetric encryption key for external use

### ISSUE THREAD

**Issue by dopstar** [tpm2-software/tpm2-tools#3246]
After I have created the AES key for symmetric encryption and decryption using https://github.com/tpm2-software/tpm2-tools/blob/master/man/tpm2_encryptdecrypt.1.md#create-an-aes-key , the output looks like:

```
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|noda|decrypt
  raw: 0x20472
type:
  value: symcipher
  raw: 0x25
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
symcipher: 26b4706559cc22d818f66217855fcd0af23d2780d463699abec6e5733d9d7d29
```

I have persisted the encryption key using `tpm2_evictcontrol` with some handle `0x8XXXXXXXX`.

I would like to have the encryption key (ie read it out of the tpm to stdout or to file) so that I can use it on an external device that doesnt have any tpm. What is the command to extract it from the tpm?
