### ISSUE TITLE
yaml_uefi_platfwblob2 assumes BlobDescription is NUL-terminated ASCII but that's not always true

### ISSUE THREAD

**Issue by tklengyel** [tpm2-software/tpm2-tools#3455]
TCG PCP 10.2.5 says the following: 

> a. For event type EV_POST_CODE2, the strings defined in Section 3.3.4.1 PCR[0] – SRTM, POST BIOS, and Embedded Drivers and Table 13 EV_POST_CODE2 Strings SHALL be used. The string SHALL be encoded in printable, 8-bit ASCII in the BlobDescription field and SHALL NOT be NUL Terminated.
> b. For event type EV_EFI_PLATFORM_FIRMWARE_BLOB2, the BlobDescription SHALL be encoded in printable, 8-bit ASCII. The strings are vendor defined.

It does not specify whether the ASCII is NUL-terminated or not for BLOB2 and there are BIOS implementations where this will NOT be NULL-terminated.

```
- EventNum: 6
  PCRIndex: 0
  EventType: EV_EFI_PLATFORM_FIRMWARE_BLOB2
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "..."
  EventSize: 32
  Event:
    BlobDescriptionSize: 15
    BlobDescription: "46565f4d41494e5f575241505045"
```

When we use the [EFI version of the log parser](https://github.com/tpm2-software/tpm2-tcti-uefi/blob/master/example/tcg2-get-eventlog.c) we see the following:

```
  PCRIndex: 0
  EventType: Unknown event type (0x8000000A)
  DigestCount: 1
    AlgorithmId: EFI_TCG2_BOOT_HASH_ALG_SHA256 (0xB)
    Digest: 32 bytes
    ....
  Event: 32 bytes
  00000000: 0F 46 56 5F 4D 41 49 4E-5F 57 52 41 50 50 45 52  *.FV_MAIN_WRAPPER*```
```

While the TCG spec is evidently ambiguous here I think it would be safer to assume that it would be consistent across the different event types how this ASCII in BlobDescription would be represented. I would suggest updating https://github.com/tpm2-software/tpm2-tools/blob/6d062650d59eb256224c74a8d1417071d995cf0b/lib/tpm2_eventlog_yaml.c#L786 to call bytes_to_str with `blobdescsize+1`.
